No margin column variant
hlxsites/sunstar pull request #256
Opened 2023-11-01 11:42 UTC by dnbute

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<gh-issue-id>

Test URLs:
- Original: https://www.sunstar.com/aboyt/history
- Before: https://main--sunstar--hlxsites.hlx.live/about/history
- After: https://no-margin-columns--sunstar--hlxsites.hlx.live/about/history

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

2023-11-01 15:44 UTC, ehrro requested changes
Hello @dnbute 

You need to keep this selector for the column to be displayed in row unless we want to have small margin not displayed in row but in column (which in this case shouldn't be called small margin :D)

![image](https://github.com/hlxsites/sunstar/assets/1226479/3de830b0-97ae-4c15-9bc9-115b338aa974)

Check on this page:
https://no-margin-columns--sunstar--hlxsites.hlx.live/about/philosophy

If you can just use the selector for small-margin to have different margin I guess this would work. Again I am not sure what is the wanted result.
![image](https://github.com/hlxsites/sunstar/assets/1226479/d529b4b0-56d0-474e-8b29-e657f97954ef)

Thanks.

2023-11-02 08:18 UTC, dnbute commented
@ehrro I fixed that, I somehow missed the `flex-direction` change, thanks for pointing it out
The purpose of this variant is for stuff like this where the default margin for the columns would push the text below it way too low, so we basically want it to be "inline" (not sure it's the best term but I hope it makes sens) with the rest of the paragraphs

With `small-margin`
<img width="707" alt="Screenshot 2023-11-02 at 10 15 51" src="https://github.com/hlxsites/sunstar/assets/44490413/3ac4e8a1-f706-40ef-b3f2-c09aae330546">

Without `small-margin`
<img width="733" alt="Screenshot 2023-11-02 at 10 16 10" src="https://github.com/hlxsites/sunstar/assets/44490413/6d4b925e-a56c-41be-b4ea-4ace1a05000c">

@jindaliiita also has some use cases for this

2023-11-02 08:25 UTC, ehrro commented
Actually I was looking for that variant for one of the use cases. Thanks It's all good now. 
![image](https://github.com/hlxsites/sunstar/assets/1226479/411410b1-701f-4a43-9a12-266b1af143e9)

2023-11-02 08:26 UTC, ehrro approved these changes

2023-11-02 09:19 UTC, merged