Removed 'Engineering'
hlxsites/sunstar pull request #26
Opened 2023-09-15 12:18 UTC by sdmcraft

Test URLs:
- Before: https://main--sunstar--hlxsites.hlx.page/
- After: https://remove-engg--sunstar--hlxsites.hlx.page/

- [ ]  If you are adding a new block or a variation to an existing block, has it been added in the [block-library](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/sunstar/sunstar/sidekick/library.xlsx?d=w7f8a415fe192444caa87806b565bb62d&csf=1&web=1&e=oJWCS0) ?

2023-09-15 12:27 UTC, bosschaert approved these changes

2023-09-15 12:28 UTC, jindaliiita requested changes

2023-09-15 12:28 UTC, jindaliiita commented on tools/importer/import-footer.js
> -      if (!a.href.includes('sunstar-engineering') && !a.href.includes('sunstarfoundation')) {
@sdmcraft Don't change here this is intentional

2023-09-16 17:18 UTC, jindaliiita approved these changes
LGTM Thanks

2023-09-17 15:53 UTC, JiangLong2019 approved these changes

2023-09-18 04:32 UTC, merged